#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set system.@imm_init[0].lang="1"
	uci -q commit system
fi
uci set luci.main.mediaurlbase='/luci-static/kucat'
uci commit luci
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
	uci -q set fstab.@global[0].anon_mount="1"
	uci -q commit fstab

	uci -q set system.@imm_init[0].anon_mount="1"
	uci -q commit system
fi

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'
EOF
uci commit system

sed -i 's,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system
# docker mirror

# firewall
uci set firewall.@defaults[0].fullcone='1'
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall
# upnp
uci set upnpd.config.enabled='1'
uci commit upnpd
service miniupnpd restart

ln -sf "/sbin/ip" "/usr/bin/ip"

if [ -f /etc/config/dockerd ] && [ $(grep -c edu /etc/config/dockerd) -eq '0' ]; then
    uci add_list dockerd.globals.registry_mirrors='https://docker.mirrors.sjtug.sjtu.edu.cn'
    uci commit dockerd
fi

sed -i '/lcp-echo/d' /etc/ppp/options
echo "lcp-echo-failure 10" >>  /etc/ppp/options 
echo "lcp-echo-interval 200" >>  /etc/ppp/options
sed -i 's/immortalwrt.org/openwrt.org/g'  /etc/config/luci

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
cat /etc/openwrt_release1 >> /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release
sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

# disable coremark
sed -i '/coremark/d' /etc/crontabs/root

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
