#!/bin/sh
uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q set system.@imm_init[0].lang="1"
fi
if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
	uci -q set fstab.@global[0].anon_mount="1"
	uci -q commit fstab
	uci -q set system.@imm_init[0].anon_mount="1"
fi

uci commit system
uci set luci.main.mediaurlbase='/luci-static/kucat'
uci commit luci

# upnp
uci set upnpd.config.enabled='1'
uci commit upnpd
/etc/init.d/miniupnpd restart
# firewall
uci set firewall.@defaults[0].fullcone='1'
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall


ln -sf "/sbin/ip" "/usr/bin/ip"

[ ! -e "/bin/bash" ] || sed -i "s|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g" "/etc/passwd"
sed -i '/lcp-echo/d' /etc/ppp/options
echo "lcp-echo-failure 10" >>  /etc/ppp/options 
echo "lcp-echo-interval 200" >>  /etc/ppp/options
sed -i 's/immortalwrt/openwrt/g' /etc/config/luci
sed -i 's/immortalwrt/openwrt/g' /etc/opkg/distfeeds.conf

sed -i '/coremark/d' /etc/crontabs/root
crontab /etc/crontabs/root
[ -f /etc/ezopenwrt_version ]  && { 
    sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
    new_DISTRIB_REVISION=`cat  /etc/ezopenwrt_version`
    echo "DISTRIB_DESCRIPTION='EzOpWrt "${new_DISTRIB_REVISION}"'" >> /etc/openwrt_release
}

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
